name: Package Repository
run-name: |
  ${{ github.event_name == 'schedule' && '⏰ Scheduled build' || '' }}
  ${{ github.event_name == 'push' && format('🌱 Push build - {0}', github.event.head_commit.message) || '' }}

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [ master ]

env:
  QEMU_VERSION: 11.1.1
  REPOSITORY: hyperion-project
  SECRET_DOCKER_CI: ${{ secrets.DOCKER_CI }}

jobs:

  build_qemu:
    name: 🐧 Build QEMU
    runs-on: ubuntu-latest
    outputs:
      QEMU_VERSION: ${{ env.QEMU_VERSION }}
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v7

      - name: ✅ Determine current Repository
        if: ${{ !startsWith(github.repository, env.REPOSITORY) }}
        run: echo "REPOSITORY=$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: 🔑 Login to GitHub Container Registry
        if: ${{ env.SECRET_DOCKER_CI != null }}
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CI }}

      - name: 👷 Build and 🚀 Push
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          file: qemu
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.REPOSITORY }}/qemu:${{ env.QEMU_VERSION }}
          labels: org.opencontainers.image.source=https://github.com/${{ env.REPOSITORY }}
          provenance: mode=max
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: QEMU_VERSION=${{ env.QEMU_VERSION }}

  build_matrix:
    name: 🐧 ${{ matrix.os.description }}
    needs: build_qemu
    strategy:
      fail-fast: false
      matrix:
        os: [
          # # Ubuntu
          # { distribution: ubuntu,     codename: jammy,       description: Ubuntu 22.04 LTS (Jammy Jellyfish),  target_platform: "['amd64', 'arm64', 'armv7', 'riscv64']" },
          # { distribution: ubuntu,     codename: noble,       description: Ubuntu 24.04 LTS (Noble Numbat),     target_platform: "['amd64', 'arm64', 'armv7', 'riscv64']" },
          # { distribution: ubuntu,     codename: resolute,    description: Ubuntu 26.04 LTS (Resolute Raccoon), target_platform: "['amd64', 'arm64', 'armv7']" },
          # { distribution: ubuntu,     codename: stonking,    description: Ubuntu 26.10 (Stonking Stingray),    target_platform: "['amd64', 'arm64', 'armv7']" },

          # # Debian
          # { distribution: debian,     codename: bookworm,    description: Debian 12.x (Bookworm),              target_platform: "['amd64', 'arm64', 'armv6', 'armv7']" },
          # { distribution: debian,     codename: trixie,      description: Debian 13.x (Trixie),                target_platform: "['amd64', 'arm64', 'armv6', 'armv7', 'riscv64']" },
          # { distribution: debian,     codename: forky,       description: Debian 14.x (Forky),                 target_platform: "['amd64', 'arm64', 'armv6', 'armv7', 'riscv64']" },

          # # Fedora
          # { distribution: fedora,     codename: 42,          description: Fedora 42,                           target_platform: "['amd64', 'arm64']" },
          # { distribution: fedora,     codename: 43,          description: Fedora 43,                           target_platform: "['amd64', 'arm64']" },
          # { distribution: fedora,     codename: 44,          description: Fedora 44,                           target_platform: "['amd64', 'arm64']" },
          # { distribution: fedora,     codename: 45,          description: Fedora 45,                           target_platform: "['amd64', 'arm64']" },
          # { distribution: fedora,     codename: 46,          description: Fedora 46,                           target_platform: "['amd64', 'arm64']" },

          # openSUSE
          { distribution: leap,       codename: 16.0,        description: openSUSE Leap,                       target_platform: "['amd64', 'arm64']" },
          { distribution: tumbleweed, codename: latest,      description: openSUSE Tumbleweed,                 target_platform: "['amd64', 'arm64']" },
        ]

    uses: ./.github/workflows/qt6.yml
    secrets: inherit
    with:
      distribution: ${{ matrix.os.distribution }}
      codename: ${{ matrix.os.codename }}
      target_platform: ${{ matrix.os.target_platform }}
      qemu_version: ${{ needs.build_qemu.outputs.QEMU_VERSION }}
      cmake_version: 4.4.3

  cleanup:
    name: 🧹 Cleanup untagged images
    needs: build_matrix
    if: ${{ needs.build_matrix.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: 🔑 Login to GitHub Container Registry
        if: ${{ env.SECRET_DOCKER_CI != null }}
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CI }}

      - name: 🧹 Cleanup
        if: ${{ env.SECRET_DOCKER_CI != null }}
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.DOCKER_CI }}
          packages: "*"
          expand-packages: true
          delete-untagged: true
          delete-partial-images: true
          delete-orphaned-images: true
          validate: true